### ISSUE TITLE
App name was changed into the FlexibleRichTextView's name

### ISSUE THREAD

**Issue by WaylanPunch** [daquexian/FlexibleRichTextView#2]
Main project's name was overrided by FlexibleRichTextView library

**Comment by daquexian** [comment]
Hmm.. I'll try to reproduce it later.. I'm busy with homework now, haha

**Comment by daquexian** [comment]
Thank you for your issue :)

**Comment by daquexian** [comment]
@WaylanPunch Could you provide more details? I couldn't reproduce it.

**Comment by WaylanPunch** [comment]
Use gradle to add library, main project's app name will be **FlexibleRichTextView**

**Comment by daquexian** [comment]
@WaylanPunch Please try the new version `0.8.2`

**Comment by WaylanPunch** [comment]
Thanks
