### ISSUE TITLE
app_name 被强制设置为’FlexibleRichTextView‘

### ISSUE THREAD

**Issue by bubifengyun** [daquexian/flexibleRichTextView#25]
本人菜鸟，看到这个，按着步骤来，结果发现`app_name`被强行更改为’FlexibleRichTextView‘了，在设置为包时，可否把 res/strings.xml 里的内容略过，谢谢啦。

**Comment by lxygithub** [comment]
把源码下载下来自己搞一搞就行了，作者估计把这个项目给忘了

**Comment by LittleBigDevil** [comment]
新建values-zh的文件夹放到res目录下，再在里面新建values-zh.xml文件，写上
`
<resources>
    <string name="app_name">APP名字</string>
</resources>
`
就行了，把库原本的values-zh覆盖掉就ok

**Comment by bubifengyun** [comment]
> 新建values-zh的文件夹放到res目录下，再在里面新建values-zh.xml文件，写上
> `<resources> <string name="app_name">APP名字</string> </resources>`
> 就行了，把库原本的values-zh覆盖掉就ok

非常感谢，问题解决了。
