### ISSUE TITLE
有没有更好的解决方案啊

### ISSUE THREAD

**Issue by tianshaokai** [daquexian/FlexibleRichTextView#6]
在android 端展示latex 公式有没有更好的解决方案 啊

**Comment by daquexian** [comment]
You can check out [this](https://github.com/kexanie/MathView), which is based on WebView and MathJax

**Comment by tianshaokai** [comment]
@daquexian  用了MathJax 就成了h5 app, 如何用原生的去展示呢？

**Comment by daquexian** [comment]
@tianshaokai 其实我也在找原生的方法。。但是我没有找到像样的 Java 的 LaTeX 库，所以如果不用 WebView 的话大概只能找一个 c/c++ 的库了

**Comment by daquexian** [comment]
不过现在混合开发是大势所趋-w-
