### ISSUE TITLE
修改文本大小

### ISSUE THREAD

**Issue by a3586684q** [daquexian/FlexibleRichTextView#7]
我想要修改文本大小，找了下好像没有对应的方法。@daquexian

**Comment by zohar-soul** [comment]
可以自己加个标签解析下即可

**Comment by a3586684q** [comment]
求一个示例@zohar-soul

**Comment by zohar-soul** [comment]
@a3586684q 
先增加标签
`        setSizeStartLabels("[size=\\s]");
        setSizeEndLabels("[/size]");`
然后依次处理下去
最后 放大一下字体就ok
`  textWithFormula.setSpan(new RelativeSizeSpan(f), 0, textWithFormula.length(), Spanned.SPAN_INCLUSIVE_EXCLUSIVE);`

**Comment by a3586684q** [comment]
好像不是这个类的方法
`FlexibleRichTextView richTextView;
richTextView = (FlexibleRichTextView) findViewById(R.id.test_text);
richTextView.setText("$S_{0}(t)>0$");`
比如这个代码，不管我怎么设置控件的大小，文字都是那么大。

**Comment by zohar-soul** [comment]
@a3586684q 
控件大小当然和文字大小没关系了
我说的第一个在源码的Tokenizer class里
第二个在FlexibleRichTextView 里

**Comment by a3586684q** [comment]
@zohar-soul 
不太懂  android开发不怎么会。
目的是想解决文字大小的问题。能不能给一个完整一些的示例。
就比如我上面的那个文字，怎么设置大小。

**Comment by zohar-soul** [comment]
@a3586684q 
我已经说了啊
你去看下源码你就明白我意思了
你要解决文字大小的问题
需要在很多地方做更改 我只能给你描述步骤 是没法给你贴完整代码的。。
思路就是原作者readme中写的

> 标签 在 这里 查看默认标签。要自定义标签，请使用 set***Labels 方法，如 setBoldStartLabels("<b>", "[b]")。
[https://github.com/daquexian/FlexibleRichTextView/blob/master/README.zh-cn.md](url)

**Comment by a3586684q** [comment]
@zohar-soul 
如果太麻烦就算了，但是还是谢谢你。
不是做这个的，投入不了那么多时间，而且我java和android都是半吊子。

**Comment by zohar-soul** [comment]
@a3586684q 
不客气

**Comment by daquexian** [comment]
蟹蟹你们对这个项目的关注。。受宠若惊。。最近特别忙所以难以抽出时间维护这个项目，不过等到有时间一定会更新的 :)
