### ISSUE TITLE
在recyclerview 里面使用这个控件之后  ，滚动条变得很不均匀 ，导致惯性滚动状态下会瞬间滚过很远的距离。。

### ISSUE THREAD

**Issue by zohar-soul** [daquexian/FlexibleRichTextView#8]
大佬有解决方案嘛？

**Comment by zohar-soul** [comment]
我感觉是recyclerview 缓存机制导致的
比如第一个是主楼特别长的帖子
下面是回复
那么当滚出去主楼后 他不被计算在整个滚动列表上了 导致recycler估计滚动条和惯性滚动距离出了问题

**Comment by daquexian** [comment]
蟹蟹乃的关注。。最近不是很有时间维护这个库。。乃是从上往下滑的时候碰到这个问题的吗

**Comment by zohar-soul** [comment]
@daquexian 
从下往上的时候。。

**Comment by daquexian** [comment]
@zohar-soul 了解了，我也碰到过。因为有一些东西是动态加载的，从上面滑下来的那一层楼的高度突然变大，所以就看起来像是突然往上滑了很多。如果我猜的这个原因没错的话，就需要针对 RecyclerView 做一些设置了，我这个库应该是没办法解决这个问题的0.0

或者我可以搞个功能做到在滑动的时候停止更新。不过不一定有时间，乃可以看看乃那边有没有什么 workaround

**Comment by zohar-soul** [comment]
@daquexian 
好的谢谢啦
